backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Website Content"
    files:
      - name: "product_list"
        label: "Product List"
        file: "products.json"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Product Name", name: "name", widget: "string"}
              - {label: "English Description", name: "desc_en", widget: "string"}
              - {label: "Traditional Chinese Description", name: "desc_hk", widget: "string"}
              - {label: "Simplified Chinese Description", name: "desc_cn", widget: "string"}
